# Generated by Django 4.1 on 2022-08-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_author_article_authorid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authorId',
            new_name='author',
        ),
    ]
